---
- name: Create .htaccess file with environment variables
  shell: |
    chdir={{ansistrano_release_path.stdout}}
    echo "SetEnv APP_ENV prod" > {{ansistrano_shared_path}}/htaccess
    echo "SetEnv APP_SECRET 5a9e4a387ef935d643d8d37441315167" >> {{ansistrano_shared_path}}/htaccess
    echo "SetEnv DATABASE_URL mysql://looking4beer_dbu:9ymXVxybTjBHgRZC3faA@data.looking4.beer:3306/data_looking4beer" >> {{ansistrano_shared_path}}/htaccess
    echo "SetEnv MAILER_USER gaby.quiles@gmail.com" >> {{ansistrano_shared_path}}/htaccess
    cat {{ ansistrano_deploy_to }}/public/.htaccess >> {{ansistrano_shared_path}}/htaccess
    cp {{ansistrano_shared_path}}/htaccess {{ ansistrano_deploy_to }}/public/.htaccess